# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160623_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(default='CDG', max_length=3),
            preserve_default=False,
        ),
    ]
