# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='type',
            new_name='typeCol',
        ),
    ]
