# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='platform',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
    ]
